services:
  # --- PROFILE 1: CLIENT-SERVER SYSTEM ---

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      # This service belongs to the 'client-server' profile
      - client-server

  server:
    build: .
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    profiles:
      # This service also belongs to the 'client-server' profile
      - client-server

  # ADDED: Frontend service
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    profiles:
      # The frontend is also part of the 'client-server' profile
      - client-server

  # --- PROFILE 2: P2P DEMONSTRATION ---

  p2p-node:
    build:
      context: ./p2p-demo
    container_name: p2p-node
    profiles:
      # This service belongs to the 'p2p' profile
      - p2p