services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tdl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: .
    container_name: api-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://user:password@postgres_db:5432/tdl_db"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - server

volumes:
  postgres-data: