services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    # This looks for 'Dockerfile' in the current directory
    build: .
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq