services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    profiles:
      - client-server

  server:
    build: .
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    volumes:
      - ./config.yaml:/app/config.yaml
    profiles:
      - client-server

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    profiles:
      - client-server
