services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1884:1883"
      - "9001:9001" 
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    profiles:
      - client-server
    # --- ДОБАВЛЕНО ---
    networks:
      - default

  server:
    build: .
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ./config.yaml:/app/config.yaml
    profiles:
      - client-server
    # --- ДОБАВЛЕНО ---
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
    profiles:
      - client-server
    # --- ДОБАВЛЕНО ---
    networks:
      - default

# --- Явно определяем сеть ---
networks:
  default:
    driver: bridge