services:
  # --- ПРОФИЛЬ 1: КЛИЕНТ-СЕРВЕРНАЯ СИСТЕМА ---

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      # Этот сервис принадлежит профилю 'client-server'
      - client-server

  server:
    build: .
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    profiles:
      # И этот сервис тоже принадлежит профилю 'client-server'
      - client-server

  # --- ПРОФИЛЬ 2: P2P ДЕМОНСТРАЦИЯ ---

  p2p-node:
    build:
      # Собираем образ из папки p2p-demo
      context: ./p2p-demo
    container_name: p2p-node
    profiles:
      # Этот сервис принадлежит профилю 'p2p'
      - p2p